---
- name: nginx install
  hosts: all
  become: yes
  tasks:
    - name: nginx installing
      apt:
        name: nginx
        state: present
        update_cache: yes
    - name: nginx running
      service:
        name: nginx
        state: started
        enabled: yes
    - name: docker add
      shell: sudo apt-get install docker
...
